### ISSUE TITLE
Error: object 'fin_conf' not found

### ISSUE THREAD

**Issue by CharlieOuthwaite** [CharlieOuthwaite/LUCC_ByOrder_paper#1]
Script 2_SimpleLUIModels

Lines 433 and 462: include mention of fin_conf, but this has not been created elsewhere in the script. @kyra-smith can you look into this please?

**Comment by kyra-smith** [comment]
fin_conf is created and printed in the global environment by the 'predict_effects' function in '0_Functions.r'. I've run through lines 423 to 466 (from the updated 2_SimpleLUIModels script) with no issues. Are you receiving any other errors?

**Comment by CharlieOuthwaite** [comment]
It was throwing and error but now seems to be fine. Of course! Might have been an issue of missing packages on my new laptop. Sorry for the bother!
